### ISSUE TITLE
Implement Logo

### ISSUE THREAD

**Issue by FrancescoSTL** [FrancescoSTL/LionBlock#12]
We need a logo which is the button users click-on in the browser. Currently that it is the [icon which is a planet](https://github.com/FrancescoSTL/LionBlock/blob/master/icon.png). Just replace that file with the logo.

Also, when the add-on is "on", the logo should change. Doesn't matter whether the back-end is functional, just change the logo when the front-end slider is set to on or off.

**Comment by nhaghighi** [comment]
I have designed 3 logo's for our team to review in our meeting 
![lionlogopro3](https://cloud.githubusercontent.com/assets/25942336/24155754/aed55d82-0e22-11e7-80be-2c38f79e5749.png)
![projectlionlogo](https://cloud.githubusercontent.com/assets/25942336/24155752/aec2e06c-0e22-11e7-8e6e-fb91ad79a1ed.png)
![lionlogopro2](https://cloud.githubusercontent.com/assets/25942336/24155753/aecd1708-0e22-11e7-9b92-6dfed61dc5b9.png)

**Comment by FrancescoSTL** [comment]
Thanks @Madeluccar
